# Streamlit Secrets 설정 파일
# 로컬 테스트용 - 이 파일은 GitHub에 업로드하지 마세요!

# VModel AI API 키 (https://vmodel.ai에서 발급)
VMODEL_API_KEY = "your-vmodel-api-key-here"

# 추가 설정 (선택사항)
DEBUG = true
MAX_IMAGE_SIZE = 10485760  # 10MB
